name: dotnet package
 
on: 
 push:
    branches: ["develop", "skip"]
 pull_request: 
    branches: ["master"]
jobs:
  build:
 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
 
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity d -p:CollectCoverage=true -p:CoverletOutput=/TestResults/coverage.opencover.xml -p:CoverletOutputFormat=opencover
      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v3"
        with: 
          files: SpaceBattle.Lib.Test/TestResults/coverage.opencover.xml